name: XFCE Desktop in Browser (NoVNC)

on:
  workflow_dispatch:   # manual start

jobs:
  desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Update system and install XFCE + VNC
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends  xfce4 xfce4-terminal  thunar file-roller thunar-archive-plugin  mousepad xfce4-taskmanager xfce4-screenshooter galculator ristretto tigervnc-standalone-server novnc websockify dbus-x11 x11-utils x11-xserver-utils  curl wget unzip
          
      - name: Setup VNC password
        run: |
          mkdir -p ~/.vnc
          echo "mypassword" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          cat > ~/.vnc/xstartup <<'EOF'
          #!/bin/sh
          unset SESSION_MANAGER
          unset DBUS_SESSION_BUS_ADDRESS
          exec dbus-launch --exit-with-session startxfce4
          EOF
          chmod +x ~/.vnc/xstartup

      - name: Start VNC server
        run: |
          vncserver :1 -geometry 1280x800 -depth 24

      - name: Start NoVNC (websockify)
        run: |
          websockify --web /usr/share/novnc/ 8080 localhost:5901 &
          sleep 5

      - name: Install Cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start tunnel to NoVNC
        run: |
          cloudflared tunnel --url http://localhost:8080 --no-autoupdate > tunnel.log 2>&1 &
          sleep 15
          echo "======== Access URL (NoVNC) ========"
          grep -Eo "https://[0-9a-zA-Z\.-]+\.trycloudflare.com" tunnel.log || true
          echo "===================================="

      - name: Keep alive until manually stopped
        run: |
          echo "Desktop is running! Stop manually with 'Stop workflow'."
          sleep infinity
